"use client";

import { useState } from "react";
import { CheckCircle, Circle, Loader2 } from "lucide-react";

type DigestedInfo = { topicSummary?: string; knownFacts?: string[] };

/**
 * Questionnaire Form Component
 * Displays clarification questions as form fields with inferred types
 * 
 * This is a reusable component for displaying clarification questions
 * generated by the generateClarificationQuestions action.
 */
export default function QuestionnaireForm({
  questions = [],
  digestedInfo = {} as DigestedInfo,
  onSubmit,
  onCancel,
  isLoading = false,
}: {
  questions?: any[];
  digestedInfo?: DigestedInfo;
  onSubmit: (answers: Record<string, string>) => void;
  onCancel?: () => void;
  isLoading?: boolean;
}) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [selectedOptions, setSelectedOptions] = useState<Record<string, string>>({});
  const [otherValues, setOtherValues] = useState<Record<string, string>>({});

  const handleAnswerChange = (questionId: string, value: string, inputType: string) => {
    if (inputType === "multiple_choice") {
      setSelectedOptions(prev => ({ ...prev, [questionId]: value }));
      // Clear "other" value if not "Other" is selected
      if (value !== "Other") {
        setOtherValues(prev => {
          const newValues = { ...prev };
          delete newValues[questionId];
          return newValues;
        });
      }
    } else {
      setAnswers(prev => ({ ...prev, [questionId]: value }));
    }
  };

  const handleOtherValueChange = (questionId: string, value: string) => {
    setOtherValues(prev => ({ ...prev, [questionId]: value }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    // Combine answers: use selected option or "other" value for multiple_choice
    const finalAnswers: Record<string, string> = {};
    questions.forEach((q: any) => {
      if (q.inputType === "multiple_choice") {
        const selected = selectedOptions[q.questionId];
        if (selected === "Other" && otherValues[q.questionId]) {
          finalAnswers[q.questionId] = otherValues[q.questionId];
        } else {
          finalAnswers[q.questionId] = selected || "";
        }
      } else {
        finalAnswers[q.questionId] = answers[q.questionId] || "";
      }
    });

    onSubmit(finalAnswers);
  };

  const isFormValid = () => {
    return questions.every((q: any) => {
      if (q.inputType === "multiple_choice") {
        const selected = selectedOptions[q.questionId];
        if (selected === "Other") {
          return otherValues[q.questionId]?.trim();
        }
        return selected;
      }
      return answers[q.questionId]?.trim();
    });
  };

  const renderQuestionField = (question: any) => {
    const { questionId, question: questionText, inputType, options, placeholder, helpText, required } = question;

    switch (inputType) {
      case "multiple_choice":
        return (
          <div className="space-y-2">
            {options?.map((option: string, idx: number) => (
              <label
                key={idx}
                className={`flex items-center gap-3 p-3 rounded-lg border-2 cursor-pointer transition-all ${
                  selectedOptions[questionId] === option
                    ? "border-primary bg-primary/5"
                    : "border-gray-200 hover:border-gray-300"
                }`}
              >
                <input
                  type="radio"
                  name={questionId}
                  value={option}
                  checked={selectedOptions[questionId] === option}
                  onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
                  className="sr-only"
                />
                {selectedOptions[questionId] === option ? (
                  <CheckCircle className="w-5 h-5 text-primary flex-shrink-0" />
                ) : (
                  <Circle className="w-5 h-5 text-gray-400 flex-shrink-0" />
                )}
                <span className="flex-1">{option}</span>
              </label>
            ))}
            {selectedOptions[questionId] === "Other" && (
              <input
                type="text"
                value={otherValues[questionId] || ""}
                onChange={(e) => handleOtherValueChange(questionId, e.target.value)}
                placeholder="Please specify..."
                className="w-full mt-2 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
              />
            )}
            {helpText && (
              <p className="text-sm text-gray-500 mt-2">{helpText}</p>
            )}
          </div>
        );

      case "textarea":
        return (
          <div>
            <textarea
              value={answers[questionId] || ""}
              onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
              placeholder={placeholder || "Enter your answer..."}
              rows={4}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent resize-y"
            />
            {helpText && (
              <p className="text-sm text-gray-500 mt-2">{helpText}</p>
            )}
          </div>
        );

      case "number":
        return (
          <div>
            <input
              type="number"
              value={answers[questionId] || ""}
              onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
              placeholder={placeholder || "Enter a number..."}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
            />
            {helpText && (
              <p className="text-sm text-gray-500 mt-2">{helpText}</p>
            )}
          </div>
        );

      case "boolean":
        return (
          <div className="flex gap-4">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name={questionId}
                value="yes"
                checked={answers[questionId] === "yes"}
                onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
                className="w-4 h-4 text-primary"
              />
              <span>Yes</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name={questionId}
                value="no"
                checked={answers[questionId] === "no"}
                onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
                className="w-4 h-4 text-primary"
              />
              <span>No</span>
            </label>
            {helpText && (
              <p className="text-sm text-gray-500 ml-4">{helpText}</p>
            )}
          </div>
        );

      case "email":
      case "url":
        return (
          <div>
            <input
              type={inputType}
              value={answers[questionId] || ""}
              onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
              placeholder={placeholder || `Enter ${inputType}...`}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
            />
            {helpText && (
              <p className="text-sm text-gray-500 mt-2">{helpText}</p>
            )}
          </div>
        );

      default: // text
        return (
          <div>
            <input
              type="text"
              value={answers[questionId] || ""}
              onChange={(e) => handleAnswerChange(questionId, e.target.value, inputType)}
              placeholder={placeholder || "Enter your answer..."}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent"
            />
            {helpText && (
              <p className="text-sm text-gray-500 mt-2">{helpText}</p>
            )}
          </div>
        );
    }
  };

  return (
    <div className="max-w-3xl mx-auto">
      {/* Context Summary */}
      {digestedInfo.topicSummary && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <h3 className="font-semibold text-blue-900 mb-2">What we know so far:</h3>
          <p className="text-sm text-blue-800">{digestedInfo.topicSummary}</p>
          {digestedInfo.knownFacts?.length > 0 && (
            <ul className="mt-2 text-sm text-blue-700 list-disc list-inside">
              {digestedInfo.knownFacts.slice(0, 3).map((fact: string, idx: number) => (
                <li key={idx}>{fact}</li>
              ))}
            </ul>
          )}
        </div>
      )}

      <form onSubmit={handleSubmit} className="space-y-6">
        {questions.map((question: any, idx: number) => (
          <div
            key={question.questionId || idx}
            className="bg-white border border-gray-200 rounded-lg p-6 shadow-sm"
          >
            <label className="block mb-3">
              <span className="text-lg font-semibold text-gray-900">
                {question.question}
                {question.required && <span className="text-red-500 ml-1">*</span>}
              </span>
              {question.group && (
                <span className="ml-2 text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">
                  {question.group}
                </span>
              )}
            </label>
            {renderQuestionField(question)}
          </div>
        ))}

        <div className="flex gap-4 justify-end pt-4 border-t">
          {onCancel && (
            <button
              type="button"
              onClick={onCancel}
              className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
              disabled={isLoading}
            >
              Cancel
            </button>
          )}
          <button
            type="submit"
            disabled={!isFormValid() || isLoading}
            className="px-6 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {isLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Processing...
              </>
            ) : (
              "Continue to Article Writing"
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
