import { NextResponse } from "next/server";
import { createHash } from "crypto";
import { createClient } from "@/libs/supabase/server";
import { createServiceRoleClient } from "@/libs/supabase/serviceRole";
import { meterGrant } from "@/libs/monkey/tools/metering.js";

function getAdminEmails() {
  return [
    ...(process.env.ADMIN_EMAIL ? [process.env.ADMIN_EMAIL.trim().toLowerCase()] : []),
    ...(process.env.ADMIN_EMAILS
      ? process.env.ADMIN_EMAILS.split(",").map((e) => e.trim().toLowerCase()).filter(Boolean)
      : []),
  ];
}

/** Deterministic UUID v4-shaped string from an arbitrary string (same algorithm as masterOfCoins). */
function uuidFromString(str) {
  const hex = createHash("sha256").update(str, "utf8").digest("hex");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

/**
 * POST /api/admin/grant-payg
 * Grant PAYG credits to a user by email. Uses meterGrant for a proper ledger entry.
 *
 * Body: { email, credits, reason, note, clientNonce }
 *   clientNonce — UUID generated by the client when the form opens. Same nonce = idempotent retry.
 */
export async function POST(request) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const adminEmails = getAdminEmails();
    const adminEmail = (user.email || "").toLowerCase();
    if (!adminEmails.includes(adminEmail)) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }

    const body = await request.json().catch(() => ({}));
    const { email, credits, reason, note, clientNonce } = body;

    if (!email || typeof email !== "string") {
      return NextResponse.json({ error: "email is required" }, { status: 400 });
    }
    const creditAmount = parseInt(credits, 10);
    if (!Number.isInteger(creditAmount) || creditAmount <= 0) {
      return NextResponse.json({ error: "credits must be a positive integer" }, { status: 400 });
    }
    if (!clientNonce || typeof clientNonce !== "string") {
      return NextResponse.json({ error: "clientNonce is required" }, { status: 400 });
    }

    const svc = createServiceRoleClient();

    // Resolve email → profile
    const { data: profile, error: profileError } = await svc
      .from("profiles")
      .select("id, email")
      .eq("email", email.trim().toLowerCase())
      .maybeSingle();

    if (profileError) throw profileError;
    if (!profile) {
      return NextResponse.json({ error: `No user found with email: ${email}` }, { status: 404 });
    }

    // Idempotency key derived from client nonce — same nonce = same key = safe retry, no double-grant
    const idempotencyKey = uuidFromString(`admin_grant_${clientNonce}`);

    const result = await meterGrant(svc, {
      userId: profile.id,
      action: "admin_payg_grant",
      creditAmount,
      idempotencyKey,
      meta: {
        granted_by: adminEmail,
        reason: reason || null,
        note: note || null,
      },
      target: "payg",
    });

    if (!result.ok) {
      return NextResponse.json({ error: "meterGrant failed" }, { status: 500 });
    }

    return NextResponse.json({
      ok: true,
      granted: result.granted,
      alreadyGranted: !result.granted,
      targetEmail: profile.email,
      userId: profile.id,
      credits: creditAmount,
      remainingPayg: result.remainingPayg ?? null,
    });
  } catch (e) {
    return NextResponse.json({ error: e.message ?? "Failed" }, { status: 500 });
  }
}
